const express = require('express');
const authRoutes = require('../modules/auth/auth.routes');
const salesRoutes = require('../modules/sales/sales.routes');
const cashRoutes = require('../modules/cash/cash.routes');
const cashRegistersRoutes = require('../modules/cashRegisters/cashRegisters.routes');
const productsRoutes = require('../modules/products/products.routes');
const categoriesRoutes = require('../modules/categories/categories.routes');
const usersRoutes = require('../modules/users/users.routes');
const stockRoutes = require('../modules/stock/stock.routes');
const kitchenRoutes = require('../modules/kitchen/kitchen.routes');
const afipRoutes = require('../modules/afip/afip.routes');
const invoicesRoutes = require('../modules/invoices/invoices.routes');
const tablesRoutes = require('../modules/tables/tables.routes');
const areasRoutes = require('../modules/areas/areas.routes');
const dashboardRoutes = require('../modules/dashboard/dashboard.routes');
const comandasRoutes = require('../modules/comandas/comandas.routes');
const articleTypesRoutes = require('../modules/articleTypes/articleTypes.routes');
const measurementUnitsRoutes = require('../modules/measurementUnits/measurementUnits.routes');
const articlesRoutes = require('../modules/articles/articles.routes');
const recipesRoutes = require('../modules/recipes/recipes.routes');
const kitchenTypesRoutes = require('../modules/kitchenTypes/kitchenTypes.routes');
const kitchensRoutes = require('../modules/kitchens/kitchens.routes');
const cashReasonsRoutes = require('../modules/cashReasons/cashReasons.routes');
const vatTypesRoutes = require('../modules/vatTypes/vatTypes.routes');
const suppliersRoutes = require('../modules/suppliers/suppliers.routes');
const customersRoutes = require('../modules/customers/customers.routes');
const purchaseOrdersRoutes = require('../modules/purchaseOrders/purchaseOrders.routes');

const router = express.Router();

router.get('/health', (_req, res) => res.json({ ok: true, service: 'restosur-backend' }));

router.use('/auth', authRoutes);
router.use('/sales', salesRoutes);
router.use('/cash', cashRoutes);
router.use('/cash-registers', cashRegistersRoutes);
router.use('/products', productsRoutes);
router.use('/categories', categoriesRoutes);
router.use('/users', usersRoutes);
router.use('/stock', stockRoutes);
router.use('/kitchen', kitchenRoutes);
router.use('/afip', afipRoutes);
router.use('/invoices', invoicesRoutes);
router.use('/tables', tablesRoutes);
router.use('/areas', areasRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/comandas', comandasRoutes);
router.use('/article-types', articleTypesRoutes);
router.use('/measurement-units', measurementUnitsRoutes);
router.use('/articles', articlesRoutes);
router.use('/recipes', recipesRoutes);
router.use('/kitchen-types', kitchenTypesRoutes);
router.use('/kitchens', kitchensRoutes);
router.use('/cash-reasons', cashReasonsRoutes);
router.use('/vat-types', vatTypesRoutes);
router.use('/suppliers', suppliersRoutes);
router.use('/customers', customersRoutes);
router.use('/purchase-orders', purchaseOrdersRoutes);

module.exports = router;
